buildscript {
    repositories { mavenCentral() }
}

allprojects {
    apply plugin: 'eclipse'
    apply plugin: 'idea'
    group = 'com.wildspirit'
    version = '0.1.0'
    ext {
        gdxVersion = '1.13.1'
    }
    repositories { mavenCentral() }
}

tasks.wrapper {
    validateDistributionUrl = false
}
